server:
  port: 2999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    hostname: localhost
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: dfpm-student-service
          uri: lb://dfpm-student-service
          predicates:
            - Path=/profession/**

        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/producto/**

